interface Env {
	CURSOR_WEBHOOK_URL?: string;
	CURSOR_WEBHOOK_KEY?: string;
	SLACK_SIGNING_SECRET?: string;
	LINEAR_CURSOR_WEBHOOK_URL?: string;
	LINEAR_CURSOR_WEBHOOK_KEY?: string;
	LINEAR_WEBHOOK_SECRET?: string;
}
